// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FooService.proto

#include "FooService.pb.h"
#include "FooService.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* FooService_method_names[] = {
  "/FooService/Foo",
};

std::unique_ptr< FooService::Stub> FooService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FooService::Stub> stub(new FooService::Stub(channel));
  return stub;
}

FooService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Foo_(FooService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FooService::Stub::Foo(::grpc::ClientContext* context, const ::request& request, ::response* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Foo_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::response>* FooService::Stub::AsyncFooRaw(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::response>::Create(channel_.get(), cq, rpcmethod_Foo_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::response>* FooService::Stub::PrepareAsyncFooRaw(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::response>::Create(channel_.get(), cq, rpcmethod_Foo_, context, request, false);
}

FooService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FooService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FooService::Service, ::request, ::response>(
          std::mem_fn(&FooService::Service::Foo), this)));
}

FooService::Service::~Service() {
}

::grpc::Status FooService::Service::Foo(::grpc::ServerContext* context, const ::request* request, ::response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


