// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FooService.proto
#ifndef GRPC_FooService_2eproto__INCLUDED
#define GRPC_FooService_2eproto__INCLUDED

#include "FooService.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class FooService final {
 public:
  static constexpr char const* service_full_name() {
    return "FooService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Foo(::grpc::ClientContext* context, const ::request& request, ::response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::response>> AsyncFoo(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::response>>(AsyncFooRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::response>> PrepareAsyncFoo(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::response>>(PrepareAsyncFooRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::response>* AsyncFooRaw(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::response>* PrepareAsyncFooRaw(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Foo(::grpc::ClientContext* context, const ::request& request, ::response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::response>> AsyncFoo(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::response>>(AsyncFooRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::response>> PrepareAsyncFoo(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::response>>(PrepareAsyncFooRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::response>* AsyncFooRaw(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::response>* PrepareAsyncFooRaw(::grpc::ClientContext* context, const ::request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Foo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Foo(::grpc::ServerContext* context, const ::request* request, ::response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Foo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* context, const ::request* request, ::response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFoo(::grpc::ServerContext* context, ::request* request, ::grpc::ServerAsyncResponseWriter< ::response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Foo<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Foo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Foo(::grpc::ServerContext* context, const ::request* request, ::response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Foo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Foo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::request, ::response>(std::bind(&WithStreamedUnaryMethod_Foo<BaseClass>::StreamedFoo, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Foo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Foo(::grpc::ServerContext* context, const ::request* request, ::response* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFoo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::request,::response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Foo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Foo<Service > StreamedService;
};


#endif  // GRPC_FooService_2eproto__INCLUDED
